name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://api.github.com/repos/Aircoookie/WLED/zipball/v0.15.0-b2 -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s3dev_8MB' >>platformio.ini
        echo 'build_flags = ${env:esp32s3dev_8MB.build_flags} -D WLED_ENABLE_DMX -D WLED_ENABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_ENABLE_WEBSOCKETS -D WLED_DISABLE_ALEXA -D WLED_DISABLE_2D -D CLIENT_SSID='\''"JCL-101"'\'' -D CLIENT_PASS='\''"!@#$QWER1234qwer!!!"'\'' -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_BH1750 -D USERMOD_AUTO_SAVE -D USERMOD_MULTI_RELAY -D USERMOD_PIRSWITCH -D USERMOD_BME280 -D USERMOD_PWM_FAN -D USERMOD_DALLASTEMPERATURE -D USERMOD_PWM_OUTPUTS -D USERMOD_SN_PHOTORESISTOR' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s3dev_8MB.lib_deps}' >>platformio.ini
        echo '  https://github.com/alwynallan/DHT_nonblocking' >>platformio.ini
        echo '  claws/BH1750 @ ^1.2.0' >>platformio.ini
        echo '  BME280@~3.0.0' >>platformio.ini
        echo '  Wire' >>platformio.ini
        echo '  OneWire@~2.3.7' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
